app:
  name: customer2-hello-world-k8s
  replicaCount: 1
image:
  repository: 67e29247.c1.gra9.container-registry.ovh.net/hello-k8s/hello-k8s
  tag: 1.0.2
service:
  port: 3000
ingress:
  host: customer2.colibrilent.ovh
